name: Build firmware

permissions:
  contents: read
  pull-requests: write
  
on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build-avr:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout repository
      uses: actions/checkout@v4
     
    - name : make 01
      working-directory: AVR_Code
      uses: brentfpage/action-avr-make@run_make_in_selected_dir_and_for_selected_target
      with:
        target: '01'

    - name: Upload variant 01 hex artifacts
      uses: actions/upload-artifact@v4
      with:
        name: asset-hex-01
        path: AVR_Code/labrafirm*01.hex
        compression-level: 0
        if-no-files-found: error

    - name : make clean
      working-directory: AVR_Code
      uses: brentfpage/action-avr-make@run_make_in_selected_dir_and_for_selected_target
      with:
        target: clean

    - name: make 02
      working-directory: AVR_Code 
      uses: brentfpage/action-avr-make@run_make_in_selected_dir_and_for_selected_target
      with:
        target: '02'

    - name: Upload variant 02 hex artifacts
      uses: actions/upload-artifact@v4
      with:
        name: asset-hex-02
        path: labrafirm*02.hex
        compression-level: 0
        if-no-files-found: error
          

#      - name: Install GNU AVR tools and run make

        #       in the future, separate the installation of the tools and the running of make
#       - name: compile using make
#         working-directory: AVR_Code/USB_BULK_TEST
#         run: make 0x02

